version: "3.8"

services:
  users-services:
    build: ./
    ports:
      - "8003:8003"
    env_file:
      - .env

  mongo-users:
    image: mongo
    ports:
      - "27020:27017"
    volumes:
      - mongo-users:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-users:
