### Register
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "name": "marc bernal",
    "email": "marc_bernal@gmail.com",
    "password": "p@ssw0rd"
}

### Login
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "marc_bernal@gmail.com",
    "password": "p@ssw0rd"
}

### Logout
POST http://localhost:8000/users/logout


### get all users
GET http://localhost:8000/users/allusers


